# Generated by Django 3.1.12 on 2022-12-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='img_recog_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_Img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('email', models.CharField(max_length=255)),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
